# Generated by Django 4.2.5 on 2023-12-02 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nip', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='users/uploads/default.png', upload_to='users/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nim', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='users/uploads/default.png', upload_to='users/uploads/')),
            ],
        ),
    ]
