# Generated by Django 4.2.5 on 2023-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lecturer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='photo',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/'),
        ),
    ]
