# Generated by Django 4.2.5 on 2023-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_lecturer_user_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='photo',
            field=models.ImageField(default='users/uploads/default.png', upload_to='users/uploads/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='users/uploads/default.png', upload_to='users/uploads/'),
        ),
    ]
