# Generated by Django 4.2.5 on 2023-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_lecturer_photo_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan'), ('tidak diketahui', 'Tidak diketahui')], default='tidak diketahui', max_length=20),
        ),
    ]
