version: '3'

services:
  web:
    image: python:3.10.12 
    command: pip install -r requirements.txt && python manage.py runserver 0.0.0.0:1111
    volumes:
      - .:/app
    ports:
      - "1111:1111"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'colearn'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
