# Generated by Django 4.2.5 on 2023-11-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='materials/uploads/'),
        ),
    ]
