# Generated by Django 4.2.5 on 2023-12-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_material_created_at_material_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='materials/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
