# Generated by Django 4.2.5 on 2023-12-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_material_thumbnail_alter_material_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
