# Generated by Django 4.2.5 on 2023-11-24 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_schedule_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='student',
        ),
        migrations.AddField(
            model_name='presence',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='meet_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='presence',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PresenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.presence')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
