# Generated by Django 4.2.5 on 2023-11-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_presence_is_present_remove_presence_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='sks',
            field=models.IntegerField(default=0),
        ),
    ]
