# Generated by Django 4.2.5 on 2023-12-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_lecturer_user_alter_student_user'),
        ('courses', '0006_course_code_course_sks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
