# Generated by Django 4.2.5 on 2023-12-10 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0004_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='Visit',
        ),
    ]
