# Generated by Django 4.2.5 on 2023-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_commentvote_forumvote_remove_forumdislike_forum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumvote',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
