# Generated by Django 4.2.5 on 2023-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='tasks/attachments/'),
        ),
    ]
