# Generated by Django 4.2.5 on 2023-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='tasks/uploads/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='tasks/uploads/'),
        ),
    ]
