# Generated by Django 4.2.5 on 2023-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
