# Generated by Django 4.2.5 on 2023-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasksubmission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
