# Generated by Django 4.2.5 on 2023-12-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment')], default='quiz', max_length=20),
        ),
    ]
